github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Start web server
    init: |
        curl -s "https://get.sdkman.io" | bash
        source "/opt/buildhome/.sdkman/bin/sdkman-init.sh"
        mkdir -p ~/.sdkman/etc
        echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
        sdk install asciidoctorj
        mkdir -p serve
        cd asciidocs
        asciidoctorj -D ../serve index.adoc
        cp -r img ../serve
        cd ../serve
        python -m http.server 8000     
      
  - name: Download Nextflow Tutorial
    init: |
      echo 'init script' # runs during prebuild
      echo 'start script'
      curl -s https://get.nextflow.io | bash
      mkdir /workspace/bin
      eval "$(sudo /opt/conda/bin/python -m conda init --dev bash)"
      sudo su root -c "/opt/conda/bin/conda install -yq conda-build"

    command: |
      cp ./nextflow /workspace/bin/nextflow  
      export PATH=/workspace/bin:$PATH
      sudo apt install  -y tree
      sudo apt install  -y graphviz
      unset JAVA_TOOL_OPTIONS
      alias conda_activate=". /opt/conda/etc/profile.d/conda.sh; conda activate bash"
      eval "$(sudo /opt/conda/bin/python -m conda init --dev bash)"

      

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
